<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__xxZTT9p2wQ</name>
   <tag></tag>
   <elementGuidId>8e867a44-52d7-4de7-b272-ee9d12ebe25a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='xxZTT9p2wQ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xxZTT9p2wQ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49ff2a0b-2639-42b1-a8dd-3d2f36f6208e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xxZTT9p2wQ</value>
      <webElementGuid>29c766c4-11e0-4b27-8ed6-b9bd8b577751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>xxZTT9p2wQ</value>
      <webElementGuid>592b1b5d-8a57-4a9b-a753-09acf0283641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb10Small</value>
      <webElementGuid>c8dc98a5-829b-4476-88a3-d2c6d910e8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4545a386-cefb-46e1-b856-3d3cc664a365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:checkCapsLockOnOff(event)</value>
      <webElementGuid>d188f7ab-74ae-47e6-bfd4-642dcc12365b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return passkey_downHandler()</value>
      <webElementGuid>f5bfc828-0549-4eb0-994f-beee6164e1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript:checkCapsLockOnOff(event)</value>
      <webElementGuid>b24663d4-c736-4de3-8b7f-0b2b1c896809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0f70f49d-8da6-4171-a48c-4e068fab16b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>64444d3d-1b92-49cb-bf4c-bc335dc47ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>47c76924-fe3b-4c60-933f-ed726a662017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xxZTT9p2wQ&quot;)</value>
      <webElementGuid>f731a08b-50c4-4f3d-883c-abc1db60b8dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xxZTT9p2wQ']</value>
      <webElementGuid>69d12909-e392-406c-9460-282cf52c68cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mainTable']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>dc07cdb4-e55f-4704-b115-62df5a4d1d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>3889dab0-8939-4bde-902e-a6933e0879e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'xxZTT9p2wQ' and @name = 'xxZTT9p2wQ' and @type = 'password']</value>
      <webElementGuid>a1b77863-3462-4fff-b0fb-6c17352f33f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
